version: "3"

services:
  client.web:
    build:
      dockerfile: ./client.web/Dockerfile
      context: .
    image: imc-web-interface-client
    volumes:
      - ./client.web:/usr/src/app
    env_file:
      - ./.env

  service.api-gateway:
    build:
      dockerfile: ./service.api-gateway/Dockerfile
      context: .
    image: imc-web-interface-api-gateway
    volumes:
      - ./service.api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - client.web
      - service.auth
      - service.config
    links:
      - client.web
      - service.auth
      - service.config

  service.auth:
    build:
      dockerfile: ./service.auth/Dockerfile
      context: .
    image: imc-web-interface-auth
    volumes:
      - .:/go/src/imc-web-interface
    env_file:
      - ./.env

  service.config:
    build:
      dockerfile: ./service.config/Dockerfile
      context: .
    image: imc-web-interface-config
    volumes:
      - .:/go/src/imc-web-interface
    env_file:
      - ./.env
