version: '3'

services:
  client.web:
    build:
      dockerfile: ./client.web/Dockerfile
      context: .
    image: imc-web-interface-client
    volumes:
      - .:/go/src/imc-web-interface
    ports:
      - 7000:80
    env_file:
      - ./.env 

  service.auth:
    build:
      dockerfile: ./service.auth/Dockerfile
      context: .
    image: imc-web-interface-auth
    volumes:
      - .:/go/src/imc-web-interface
    ports:
      - 7001:80
    env_file:
      - ./.env 

  service.config:
    build:
      dockerfile: ./service.config/Dockerfile
      context: .
    image: imc-web-interface-config
    volumes:
      - .:/go/src/imc-web-interface
    ports:
      - 7002:80
    env_file:
      - ./.env 